image: mcr.microsoft.com/dotnet/core/sdk:3.1

pipelines:
  default:
    - step:
        name: Build and Deploy
        caches:
          - docker
        script:
          - git lfs install
          - git lfs pull
          - # Ajouter votre commande de déploiement ici
